### ISSUE TITLE
Autoplay not working on iOS

### ISSUE THREAD

**Issue by thehoodDE** [deltanet/adapt-audio#116]
The play icon changes to pause and becomes unresponsive to touch gestures, no audio is playing.

With a tap on a second audio element on the page, the first button becomes responsive again. If "Autoplay Only Once" is false, it will now play correctly when it's in the view again.

Course created using the Authoring Tool.
Tested on iPad mini 2, iOS 10.3.2.

The showcased courses play correctly on my device (e.g. https://showcase.astute-elearning.com/Packages/delta-take5-t23_GOLD_01_04_2016_2/index_lms.html#/id/co-01)

**Comment by mike-st** [comment]
Just a thought as I am struggling with this problem too in the iOS environment. Perhaps autoplay should be turned off no mater what is selected in that environment. I am thinking that will solve the problem. I will fiddle around and see what I come up with and let you know if it works or not.

**Comment by mike-st** [comment]
Hi I have fixed the issue by turning off autoplay on iOS devices. iOS is notoriously for not working well with autoplay on video and sound. I would think it would be safer personally to leave it off. Here is the autoplay fix for the "audio-controls-view.js" if you want to use it just replace these 2 items...


// Autoplay
            if (Adapt.audio.autoPlayGlobal || this.model.get("_audio")._autoplay) {
                if(!!navigator.userAgent.match(/iPad/i) || navigator.userAgent.match(/iPhone/i)) {
                    this.canAutoplay = false;
                } else {
                    this.canAutoplay = true;
                }
            } else {
                this.canAutoplay = false;
            }


            // Autoplay once
            if (Adapt.audio.autoPlayOnceGlobal == false) {
                this.autoplayOnce = false;
            } else if (Adapt.audio.autoPlayOnceGlobal || this.model.get("_audio")._autoPlayOnce) {
                if(!!navigator.userAgent.match(/iPad/i) || navigator.userAgent.match(/iPhone/i)) {
                    this.autoplayOnce = false;
                } else {
                    this.autoplayOnce = true;
                }
            } else {
                this.autoplayOnce = false;
            }

**Comment by RobertPeek** [comment]
Thanks for your input with this @mike-st 

Once the changes are fully tested it can be released @thehoodDE
