### ISSUE TITLE
Audio preference dialogue for mobiles

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt-audio#13]
Need to have some way of enabling audio on mobiles if there are no play buttons for each audio and we want autoplay :(

**Comment by dancgray** [comment]
Needs to be able to start audio on mobile and iOS devices when _showControls is not enabled for each audio element on the components. This could either be 1)  browser detection with a confirm popup to start audio just for iOS devices or 2) an extra play button on the navigation bar to start audio possibly with a hint popup that appears once below it with instructions for all instances (so we don’t have to do browser detection).

**Comment by dancgray** [comment]
See https://github.com/cgkineo/adapt-hint

**Comment by RobertPeek** [comment]
Simple prompt added. See PR:

https://github.com/deltanet/adapt-audio/pull/22

**Comment by RobertPeek** [comment]
The 'Reduced text' functionality has now resolved this as a prompt shows on module load.
