### ISSUE TITLE
Check notify popups and stop audio

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt-audio#15]
Some of the notify popups, like bookmarking confirm on revisit of a course, should stop audio. Currently the audio  continues to play.

**Comment by RobertPeek** [comment]
For the purpose of our default framework, this isn't needed as there is no audio on the first block in the PAS intro. However we do use a video that autoplays so this ideally needs to pause while notify is open. Issue for this has been added to the default_framework.
