### ISSUE TITLE
Audio plays when resizing the browser window, does not activate play button.

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt-audio#168]
## Expected Behaviour
Resizing browser window should not play audio. 

## Actual Behaviour
Resize event causes audio to play but does not activate play button which means that audio can play twice.

## Steps to Reproduce
1. Setup a component with audio set to autoplay. Autoplay once set to false.
2. Preview and resize the window, causes audio to play
3. Click play button as well.

adapt-audio v3.6.8

## Versions
  - Authoring Tool Version: v0.5.4-D
  - Framework Version: v2.2.5
  - Operating System: n/a
  - Browser: n/a

**Comment by RobertPeek** [comment]
Fixed from updating another plugin.
