### ISSUE TITLE
Framework 5 Trickle issue

### ISSUE THREAD

**Issue by css3ninja** [deltanet/adapt-audio#192]
There is an issue when having audio on the components under a block with trickle. It does not load the audio on the block/component when pressing continue on trickle. I believe this is because the page only loads the blocks/components before trickle on page load, then when continue is pressed the audio files below trickle don't load as they weren't put in on page load as trickle blocks it. 

If I navigate to the menu and then come back in the audio files will then load as trickle has been completed.

**Comment by zarek3333** [comment]
Getting this issue too. When audio is used under a trickle button on a block or component it won't load when the continue button is pressed for trickle. I have to click on the menu and then come back to the page for it to load. 

Using framework 5.15.2

**Comment by css3ninja** [comment]
I was using an older version seems to work fine now with your latest version.
