### ISSUE TITLE
Add volume slider to navigation bar audio on/off icon

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt-audio#24]
The dual functionality of the volume slider on soundcloud.com has the ideal functionality
![screen shot 2015-12-02 at 09 42 34](https://cloud.githubusercontent.com/assets/6452430/11527477/238a2cd6-98d9-11e5-9578-72087f2986cc.png)

**Comment by RobertPeek** [comment]
With the addition of the new 'Reduced text' feature I don't think the volume controller should be on the nav bar toggle button. This button now triggers a notify popup so any more functionality may be too much.

Suggest adding volume control to the 'Audio channels' in the drawer.

**Comment by RobertPeek** [comment]
Moved to Default Build Repo.
