### ISSUE TITLE
Autoplay feature is not working as I scroll down the course

### ISSUE THREAD

**Issue by mike-st** [deltanet/adapt-audio#30]
Unfortantely the Autoplay feature is not working as I scroll down the course. Is there something I am missing or is this just not implemented at this point?

**Comment by mike-st** [comment]
Auto play is not working because you reverse the true and false around. Once you switch them it will work. Here is the revised line of code...
Adapt.audio.autoPlayGlobal = Modernizr.touch ? false : Adapt.course.get('_audio')._autoplay ? false : true;

**Comment by dancgray** [comment]
Thanks for spotting this @mike-st. Quite a few of the "features" on this extension are in development. At some point I'm hoping it will get rewritten more in line with the [communities requirements](https://community.adaptlearning.org/mod/forum/discuss.php?d=614)

**Comment by mike-st** [comment]
Looks good! and it is heading in a good direction too. Nice work
