### ISSUE TITLE
example.json _audioItems._status is incorrect name and possibly not required.

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt-audio#32]
@RobertPeek is set _audioItems._status as per the example.json still used?

https://github.com/deltanet/adapt-audio/blob/master/example.json#L17

Cannot find it in any code.

**Comment by dancgray** [comment]
The use of this variable would probably be clearer if it was _enabled boolean.

**Comment by RobertPeek** [comment]
Removed _status attributes as not needed.
