### ISSUE TITLE
iPad doesn't autoplay multiple channels

### ISSUE THREAD

**Issue by RobertPeek** [deltanet/adapt-audio#49]
Tried an audio on an article set to channel 1 and an audio on a component within the article on channel 0 and it just plays the audio on the component.

**Comment by RobertPeek** [comment]
Seems to be related to this function when you select continue on the prompt when you enter the module:

setContinue: function() {
      Adapt.audio.audioStatus = 1;
      Adapt.trigger('audio:changeText', 0);
      this.playCurrentAudio(0);
      this.stopListening(Adapt, "audio:selectContinue");
},

Adding 'this.playCurrentAudio(1);' will set the autoplay on that channel too for iPad.

Bit messy though!

**Comment by dancgray** [comment]
Are you trying to play multiple <audio> clips at the same time?

If so there might be issues on iOS:
http://stackoverflow.com/questions/4445676/multi-channel-audio-support-in-the-browser-on-ios-and-android

It's quite old though :)
