### ISSUE TITLE
Pause button acting like a stop button

### ISSUE THREAD

**Issue by mike-st** [deltanet/adapt-audio#60]
Hi Just wanted to say first of all this Extension is fantastic! I haven't worked with it for a while until now, but I can tell you put a lot of new features and works great now! The only issue I am having is kind of a biggie functionality wise. When I go to press the pause button and then play it again after waiting, it starts the audio from the beginning of the track at 0.00. Which means it is more like a stop than a pause. Once you fix the pause in the extension, it'll be amazing!

**Comment by mike-st** [comment]
Meant to mention I am getting this error when I inspect the page could be related to the issue...

Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

**Comment by dancgray** [comment]
Hi @mike-st, glad you like the extension. I agree that both of these are a real issue and we aim to fix them as soon as we can.

Really appreciate the feedback 👍
