### ISSUE TITLE
Audio on menu view doesn't work in Authoring Tool

### ISSUE THREAD

**Issue by RobertPeek** [deltanet/adapt-audio#88]

**Comment by dancgray** [comment]
_type can also be "course".

https://github.com/deltanet/adapt-audio/blob/master/js/adapt-audio.js#L416

this is not an issue.

**Comment by dancgray** [comment]
outputmanager.js in authoring tool is being selective with the JSON (https://github.com/deltanet/adapt_authoring/blob/master/lib/outputmanager.js#L761) i.e adding an /en folder to the asset path only for non contentObject collections.

Also see https://github.com/deltanet/adapt_authoring/blob/master/lib/outputmanager.js#L336

**Comment by dancgray** [comment]
This will be fixed in authoring tool see https://github.com/deltanet/adapt_authoring/issues/48

**Comment by dancgray** [comment]
Fixed in https://github.com/deltanet/adapt_authoring/pull/50
